apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-nginx-deployment
  labels:
    app: app1-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-nginx
  template:
    metadata:
      labels:
        app: app1-nginx
    spec:
      containers:
        - name: app1-nginx
          image: ghcr.io/stacksimplify/kube-nginxapp1:1.0.0
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /readiness
              port: 80
              httpHeaders:
              - name: Custom-Header
                value: readinessprobe
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /liveness
              port: 80
              httpHeaders:
              - name: Custom-Header
                value: livenessprobe
            initialDelaySeconds: 5
            periodSeconds: 30   