apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configfile-cm
data:
  default.conf: |-
    server {
        listen 80 default_server;
        listen 443 ssl;
        root /usr/share/nginx/html;
        index index.html;
        ssl_certificate /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;
    }

    