apiVersion: v1
kind: Service
metadata:
  name: myapp-nginx-loadbalancer-service
  labels:
    app: myapp-nginx
spec:
  type: LoadBalancer
  selector:
    app: myapp-nginx
  ports:
    - port: 443
      targetPort: 443
